<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>UiInterface</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>WorkTracker</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.riddlersoftgames.worktracker</ApplicationId>
		<ApplicationIdGuid>20D09131-3A8A-4699-A635-26E57F2BB6C5</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.99</ApplicationDisplayVersion>
		<ApplicationVersion>32</ApplicationVersion>

		<!-- Run Windows unpackaged. Without this the app builds as MSIX, and an
		     MSIX cannot be launched by `dotnet run` or by the Windows Machine
		     profile unless the single-project MSIX tooling is switched on - which
		     is what left this project impossible to start. Only revisit if the app
		     is ever shipped through the Microsoft Store; Android packaging is
		     unaffected. See https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<!-- stamped into the assembly so the settings page can show when
		     this build was made, without anyone having to remember -->
		<BuildDate>$([System.DateTime]::UtcNow.ToString('yyyy-MM-dd'))</BuildDate>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	  <AndroidPackageFormat>aab</AndroidPackageFormat>
	  <DebugSymbols>False</DebugSymbols>
	  <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-maccatalyst|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-maccatalyst|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-windows10.0.19041.0|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-windows10.0.19041.0|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.111" />
		<PackageReference Include="Plugin.Maui.OCR" Version="1.1.1" />
		<!-- reads the text and its position out of bank statement PDFs -->
		<PackageReference Include="PdfPig" Version="0.1.15" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyMetadata Include="BuildDate" Value="$(BuildDate)" />
	</ItemGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#1A9D68" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\appiconfg.svg" Color="#1A9D68" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\dotnet_bot.svg" />
	  <None Remove="Resources\Images\paid.png" />
	  <None Remove="Resources\Images\searchicon.png" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="..\Kernel\CResult.cs" Link="Kernal\CResult.cs" />
	  <Compile Include="..\Kernel\DataCheck.cs" Link="Kernal\DataCheck.cs" />
	  <Compile Include="..\Kernel\DataSnapshot.cs" Link="Kernal\DataSnapshot.cs" />
	  <Compile Include="..\Kernel\DayNote.cs" Link="Kernal\DayNote.cs" />
	  <Compile Include="..\Kernel\DayProgress.cs" Link="Kernal\DayProgress.cs" />
	  <Compile Include="..\Kernel\DataStamp.cs" Link="Kernal\DataStamp.cs" />
	  <Compile Include="..\Kernel\Customer.cs" Link="Kernal\Customer.cs" />
	  <Compile Include="..\Kernel\CustomerMerge.cs" Link="Kernal\CustomerMerge.cs" />
	  <Compile Include="..\Kernel\Expense.cs" Link="Kernal\Expense.cs" />
	  <Compile Include="..\Kernel\ExpenseRule.cs" Link="Kernal\ExpenseRule.cs" />
	  <Compile Include="..\Kernel\StatementRecord.cs" Link="Kernal\StatementRecord.cs" />
	  <Compile Include="..\Kernel\YearlyStore.cs" Link="Kernal\YearlyStore.cs" />
	  <Compile Include="..\Kernel\Filter.cs" Link="Kernal\Filter.cs" />
	  <Compile Include="..\Kernel\Gloable.cs" Link="Kernal\Gloable.cs" />
	  <Compile Include="..\Kernel\GoCardlessRequest.cs" Link="Kernal\GoCardlessRequest.cs" />
	  <Compile Include="..\Kernel\Job.cs" Link="Kernal\Job.cs" />
	  <Compile Include="..\Kernel\JobDisplay.cs" Link="Kernal\JobDisplay.cs" />
	  <Compile Include="..\Kernel\BalanceAdjustment.cs" Link="Kernal\BalanceAdjustment.cs" />
	  <Compile Include="..\Kernel\BankAccount.cs" Link="Kernal\BankAccount.cs" />
	  <Compile Include="..\Kernel\Location.cs" Link="Kernal\Location.cs" />
	  <Compile Include="..\Kernel\Payment.cs" Link="Kernal\Payment.cs" />
	  <Compile Include="..\Kernel\PaymentDisplay.cs" Link="Kernal\PaymentDisplay.cs" />
	  <Compile Include="..\Kernel\PaymentMethod.cs" Link="Kernal\PaymentMethod.cs" />
	  <Compile Include="..\Kernel\QueryType.cs" Link="Kernal\QueryType.cs" />
	  <Compile Include="..\Kernel\RoundStats.cs" Link="Kernal\RoundStats.cs" />
	  <Compile Include="..\Kernel\ScreenshotMode.cs" Link="Kernal\ScreenshotMode.cs" />
	  <Compile Include="..\Kernel\SaveLoad.cs" Link="Kernal\SaveLoad.cs" />
	  <Compile Include="..\Kernel\TaxReporting.cs" Link="Kernal\TaxReporting.cs" />
	  <Compile Include="..\Kernel\UsefulFuctions.cs" Link="Kernal\UsefulFuctions.cs" />
	  <Compile Include="..\Kernel\WorkDay.cs" Link="Kernal\WorkDay.cs" />
	  <Compile Include="..\Kernel\WorkShare.cs" Link="Kernal\WorkShare.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Layouts\Customers.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Layouts\Jobs.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Layouts\NewCustomer.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Layouts\NewJob.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Layouts\WorkPlanner.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Layouts\BookJobFormcs.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\CalenderView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\Customers.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\Jobs.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\LinkCustomerLayout.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\NewCustomer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\NewJob.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\PaperView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\Payments.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\QuickAddCustomer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\SettingLayout.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\StatmentViewer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\StatementExpenses.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\ExpenseRules.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\SelectTaxYears.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\KeptStatements.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\BankAccounts.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\StatementReader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\IgnoredPayments.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\JobStatus.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\TidyCustomers.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\DataIssues.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\AllJobs.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\Quotes.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\Stats.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\TaxView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\TutorialWorkPlanner.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\UpdateJobInstance.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\ViewCustomerDetails.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Layouts\WorkPlanner.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Update="Resources\Images\dotnet_bot.svg">
	    <BaseSize>168,208</BaseSize>
	  </MauiImage>
	</ItemGroup>

</Project>

